### ISSUE TITLE
Integration doesn't support re-auth

### ISSUE THREAD

**Issue by jbergler** [mauro-midolo/homeassistant_electrolux_status#109]
It seems that pyelectroluxconnect is doing the right thing and reporting auth errors, however when home assistant tries to start the re-auth flow it logs this error

```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 873, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 362, in _async_handle_step
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ElectroluxStatusFlowHandler doesn't support step reauth

```

If I find some time, I will try and open a PR assuming no one beats me to it.
This seems to be a pretty straight forward example: https://github.com/jbergler/home-assistant.core/blob/4365d2973c648ab890c47f2d854e7c84215c5fc3/homeassistant/components/fritzbox/config_flow.py#L179

**Comment by jbergler** [comment]
Thanks @mauro-midolo for the very quick turn-around, it's much appreciated!
