### ISSUE TITLE
Could not log in to ElectroluxStatus, Invalid API response: Unauthorized (401)

### ISSUE THREAD

**Issue by pem884** [mauro-midolo/homeassistant_electrolux_status#115]
I started getting errors trying to log in a few hours ago. I noticed #110  and I suspect the "frigidaire" endpoint may also need to be updated upstream. I tried updating my local pyelectroluxconnect to 0.3.17 and logging in that way, and it does not work:

```python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> username = "myemail@domain.com"
>>> password = "hopeitsagoodone"
>>> import pyelectroluxconnect
>>> ses = pyelectroluxconnect.Session(username, password, region="frigidaire")
>>> ses.login()
Getting new auth token
Unauthorized (401)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\pyelectroluxconnect\Session.py", line 1061, in login
    self._createToken()
  File "C:\Python311\Lib\site-packages\pyelectroluxconnect\Session.py", line 176, in _createToken
    raise LoginError(f'{err.message} ({err.status_code})') from None
pyelectroluxconnect.Session.LoginError: Unauthorized (401)
```

Might make sense for me to create an issue upstream, right? I'll do that. Wanted to have one here as well so we can be in sync on the resolution.

**Comment by pem884** [comment]
API's were updated upstream as of this morning in v0.3.18 which did yield a new response but did not "fix" for me: I now get 403 (forbidden) instead of 401 (unauthorized). Will advise.
