### ISSUE TITLE
Invalid API response: Endpoint request timed out (504)

### ISSUE THREAD

**Issue by JosefRypacek** [mauro-midolo/homeassistant_electrolux_status#124]
I've installed this useful integration few days ago and having status of my oven `unavailable` few times a day.
The error probably comes from pyelectroluxconnect, but I think this integration should repeat the request or just mark as `unavailable` after multiple unsuccessful request if this particular error is returned.

```
2023-08-17 16:21:43.355 ERROR (SyncWorker_7) [pyelectroluxconnect.Session] Invalid API response: Endpoint request timed out (504)
2023-08-17 16:21:43.356 ERROR (MainThread) [custom_components.electrolux_status] Invalid API response: Endpoint request timed out (504)
Traceback (most recent call last):
File "/config/custom_components/electrolux_status/__init__.py", line 94, in _async_update_data
appliance_state = await self.hass.async_add_executor_job(self.api.getApplianceState, appliance)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1125, in getApplianceState
_json = self._requestApi(
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 980, in _requestApi
raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Endpoint request timed out (504)
2023-08-17 16:21:43.360 ERROR (MainThread) [custom_components.electrolux_status] Error fetching electrolux_status data:
```

See following image and "gaps" in the data.
![Snímek obrazovky 2023-08-17 v 22 12 08](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/5843126/d3696560-8bf5-4182-acd4-81dd089f7880)

**Comment by JariInc** [comment]
I'm also getting 504 gateway timeouts when trying to setup the integration. This happens before setup flow starts.

**Comment by kovacsla** [comment]
I have a same problem:

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Kezelőfelület 20230911.0 - latest
Electrolux Care Integration (Not Official) v.3.0.0

I show tow examples:

home-assistant.log:

**2023-09-18 13:50:36.706** ERROR (SyncWorker_3) [pyelectroluxconnect.Session] Invalid API response: Endpoint request timed out (504)
2023-09-18 13:50:36.710 ERROR (MainThread) [custom_components.electrolux_status] Invalid API response: Endpoint request timed out (504)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 94, in _async_update_data
    appliance_state = await self.hass.async_add_executor_job(self.api.getApplianceState, appliance)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1125, in getApplianceState
    _json = self._requestApi(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 980, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Endpoint request timed out (504)
2023-09-18 13:50:36.713 ERROR (MainThread) [custom_components.electrolux_status] Error fetching electrolux_status data: 
.
.
.
**2023-09-18 13:54:52.311** ERROR (MainThread) [custom_components.electrolux_status] Invalid API response: Endpoint request timed out (504)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 93, in _async_update_data
    connection_state = await self.hass.async_add_executor_job(self.api.getApplianceConnectionState, appliance)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1096, in getApplianceConnectionState
    _json = self._requestApi(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 980, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Endpoint request timed out (504)
2023-09-18 13:54:52.315 ERROR (MainThread) [custom_components.electrolux_status] Error fetching electrolux_status data: 

The timeline have two gap same time. 
![Timeline_gap](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/117943937/cc98b17f-fcef-4886-87e4-b8a6b777b58f)
