### ISSUE TITLE
v3.0.0 fails when trying to reconnect

### ISSUE THREAD

**Issue by hlavki** [mauro-midolo/homeassistant_electrolux_status#128]
Using latest homeassistant 2023.9.2 I get this error when trying to add this integration:
```
homeassistant  | 2023-09-17 20:03:35.804 ERROR (SyncWorker_3) [pyelectroluxconnect.Session] Exception in _getApplianceConfiguration(914500706,00,30600022): [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 242, in _getApplianceConfiguration
homeassistant  |     open(applianceConfigFilePath, "wb").write(
homeassistant  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  | FileNotFoundError: [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | 2023-09-17 20:03:35.806 ERROR (SyncWorker_3) [pyelectroluxconnect.Session] Exception in _getAppliancesList: [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 202, in _getAppliancesList
homeassistant  |     applianceProfile = self._getApplianceConfiguration(self._applianceIndex[device["appliance_id"]]["pnc"],
homeassistant  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 280, in _getApplianceConfiguration
homeassistant  |     raise Error(err) from None
homeassistant  | pyelectroluxconnect.Session.Error: [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | 2023-09-17 20:03:35.807 ERROR (SyncWorker_3) [pyelectroluxconnect.Session] Error while get Appliances list: [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | 2023-09-17 20:03:35.807 ERROR (SyncWorker_3) [pyelectroluxconnect.Session] [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | 2023-09-17 20:03:35.808 ERROR (MainThread) [custom_components.electrolux_status.config_flow] [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/config/custom_components/electrolux_status/config_flow.py", line 126, in _test_credentials
homeassistant  |     await self.hass.async_add_executor_job(client.login)
homeassistant  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
homeassistant  |     result = self.fn(*self.args, **self.kwargs)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1073, in login
homeassistant  |     raise Exception(ErrorArg) from None
homeassistant  | Exception: [Errno 2] No such file or directory: '/root/.pyelectroluxconnect/914500706_00_00.zip'
```

**Comment by Noxeus** [comment]
I can add the integration, but I can't login. I get the same error as OP and above that an error with:
`pyelectroluxconnect.Session.LoginError: No Consumer with this email: <email> (AER0802)`
I can login using the same credentials in a Python console using `pyelectroluxconnect`.

**Comment by mauro-midolo** [comment]
Please upgrade to v3.1.0
