### ISSUE TITLE
Credentials accepted but integration hit errors 

### ISSUE THREAD

**Issue by AdrianGarside** [mauro-midolo/homeassistant_electrolux_status#151]
This error originated from a custom integration.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:99
Integration: Electrolux Care Integration (documentation, issues)
First occurred: 7:37:29 PM (7 occurrences)
Last logged: 7:39:34 PM

invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 99, in _async_update_data
    app.setup(ElectroluxLibraryEntity(appliance_name, connection_state, appliance_state, appliance_profile))
  File "/config/custom_components/electrolux_status/api.py", line 319, in setup
    self.entities = [
                    ^
  File "/config/custom_components/electrolux_status/api.py", line 320, in <listcomp>
    entity.setup(data)
  File "/config/custom_components/electrolux_status/api.py", line 190, in setup
    self._state = data.get_value(self.attr, self.field, self.source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/api.py", line 33, in get_value
    return self.time_to_end_in_minutes(attr_name, field, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/api.py", line 53, in time_to_end_in_minutes
    return int(math.ceil((int(seconds) / 60)))
                          ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
P

**Comment by AdrianGarside** [comment]
Edited that line quickly to just return None and the integration appears to be working (other than the 'will finish' sensors which say Unknown which is probably correct since the oven's not in use but I expect will stay saying when in use due to my quick hack):
![image](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/26147576/d3689052-e6e4-4182-aa41-91c7a5c3a752)

I'll revisit this tomorrow when I'm more awake to craft a better fix for the empty string being encountered there.

**Comment by AdrianGarside** [comment]
This seems to work but I'm not sure yet how -1 is distinct from None as a return value:
![image](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/26147576/d1d82001-27b2-425b-a394-1009a7dbc907)

I now get:
![image](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/26147576/99b43d9f-64d8-4506-b38f-12e58f31a9bd)

**Comment by mauro-midolo** [comment]
Ciao @AdrianGarside, please give a pull request about that

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs

**Comment by AdrianGarside** [comment]
This is unrelated to that.
