### ISSUE TITLE
Login failed - Washing Machine in APAC region.

### ISSUE THREAD

**Issue by smaurer3** [mauro-midolo/homeassistant_electrolux_status#27]
Comes down to an issue (which i have raised) in the pyelectroluxconnect libray.

My device does not return a nickname.  This is what my device returns:
{'appliance_type': '914900813_00', 'appliance_id': '02024136-443E07061EDA', 'pnc': '914900813', 'elc': '00', 'sn': '02024136', 'mac': '443E07061EDA', 'cpv': '00', 'group': 'FabricCare', 'brand': 'Electrolux', 'model': 'EWF1041'}

Here is the home assistant log error:
2022-06-14 14:41:05 ERROR (MainThread) [custom_components.electrolux_status.config_flow] 'nickname'
Traceback (most recent call last):
File "/config/custom_components/electrolux_status/config_flow.py", line 84, in _test_credentials
await self.hass.async_add_executor_job(client.login)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/pyelectroluxconnect/Session.py", line 674, in login
self._getAppliancesList()
File "/usr/local/lib/python3.9/site-packages/pyelectroluxconnect/Session.py", line 185, in _getAppliancesList
"alias": device["nickname"],
KeyError: 'nickname'

**Comment by smaurer3** [comment]
[tomeko12](https://github.com/tomeko12) has updated the pyelectroluxconnect library.

Updating version number in manifest.json to 0.3.3 got this integration working for me now in home assistant.

**Comment by mavack** [comment]
Thanks @smaurer3  i did the same and restarted and also worked. Same issue

**Comment by mauro-midolo** [comment]
Ciao @smaurer3,
Release #30 includes the pyelectroluxconnect 0.3.3 library.
Please update integration.
