### ISSUE TITLE
API request error

### ISSUE THREAD

**Issue by rjcds** [mauro-midolo/homeassistant_electrolux_status#78]
Hi, thank you for this project !
For me, it works intermittently, but will randomly fail with the following errors:

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:800 
First occurred: 12:40:31 PM (3 occurrences) 
Last logged: 1:00:41 PM

API request error: HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /user-appliance-reg/users/rohone%40gmail.com/appliances (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff50e3e3f40>: Failed to establish a new connection: [Errno -3] Try again'))
API request error: HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /elux-ms/appliances/latest?pnc=xxx&elc=01&sn=xxx&states=ConnectivityState&includeSubcomponents=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff50f994b80>: Failed to establish a new connection: [Errno -3] Try again'))
API request error: HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /elux-ms/appliances/latest?pnc=xxx&elc=01&sn=xxx&states=ConnectivityState&includeSubcomponents=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff519605600>: Failed to establish a new connection: [Errno -3] Try again'))
```

and

```
This error originated from a custom integration.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:93 
Integration: Electrolux Care Integration (documentation, issues) 
First occurred: 12:40:36 PM (2 occurrences) 
Last logged: 1:00:41 PM

HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /elux-ms/appliances/latest?pnc=xxx&elc=01&sn=xxx&states=ConnectivityState&includeSubcomponents=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff50f994b80>: Failed to establish a new connection: [Errno -3] Try again'))
HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /elux-ms/appliances/latest?pnc=xxx&elc=01&sn=xxx&states=ConnectivityState&includeSubcomponents=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff519605600>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 93, in _async_update_data
    connection_state = await self.hass.async_add_executor_job(self.api.getApplianceConnectionState, appliance)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 935, in getApplianceConnectionState
    _json = self._requestApi(
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 801, in _requestApi
    raise Exception(err) from None
Exception: HTTPSConnectionPool(host='api.apac.ecp.electrolux.com', port=443): Max retries exceeded with url: /elux-ms/appliances/latest?pnc=xxx&elc=01&sn=xxx&states=ConnectivityState&includeSubcomponents=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff50f994b80>: Failed to establish a new connection: [Errno -3] Try again'))
```

Reloading the integration and restarting HA will get it to work again for a period, before the same errors come up

The Electrolux Life app works fine during the time that the integration doesn't work

Is there anything else I can do to help troubleshoot ?

**Comment by mauro-midolo** [comment]
The issue has been resolved in version v2.8.0, please update.
